New stanford header and footer styling
Stanford-Online/openedx-themes pull request #23
Opened 2018-04-26 19:47 UTC by caesar2164

- some content changes as well

@stvstnfrd, @lydiali, & @mondiaz

2018-04-26 20:52 UTC, stvstnfrd requested changes
My comments thus far are mostly superficial.
Can you remove the cosmetic changes (whitespace and comments) into a separate PR?
These unrelated changes make this more difficult to review.

2018-04-26 20:52 UTC, stvstnfrd commented on lagunita/lms/templates/su-footer.html
> +        <ul id="global-links">
Do these have to be IDs?
We can probably get away with `class`es..

2018-04-26 20:52 UTC, stvstnfrd commented on lagunita/lms/static/css/vendor/su-identity.css
> +/*
This comment doesn't add clarity; let's drop it.

And as a side note:
When code _does_ warrant comments, please don't use the long string of `=`s.
Those show up as false positives when grepping for conflict markers.

2018-04-26 20:52 UTC, stvstnfrd commented on lagunita/lms/static/css/vendor/su-identity.css
> -
Generally speaking, please split out whitespace changes into a separate PR, or at the very least, a separate commit. It makes this code significantly more difficult to review, as close to 50% of the changes are cosmetic.

2018-04-26 20:54 UTC, stvstnfrd commented
@caesar2164 Can you edit your description to include a screenshot of the current footer on https://stanford.edu for easier side-by-side comparison?

2018-04-26 21:33 UTC, caesar2164 commented on lagunita/lms/templates/su-footer.html
> +        <ul id="global-links">
This is how stanford.edu does it ¯\_(ツ)_/¯

2018-04-26 22:00 UTC, mondiaz commented
@caesar2164 Just want to make sure I'm catching everything I should be here in these before, after, and Stanford.edu screenshot comparisons.

- The 15 screenshots appear to illustrate the way the footer changes based on window size. So the first screenshots show how things compare when at their narrowest (how they might appear on a smartphone), and the last screenshots show how things compare when at full screen. Is that correct?

- The footer links are taking up two lines instead of one, and there are a few links being added, namely:
     - Emergency Info
     - Privacy Policy
     - Trademark Notice

     Am I understanding that correctly?

- The copyright string at the bottom is very slightly different when I look at the after and stanford.edu screenshots. It looks like on stanford.edu, the bottom line changes a comma to a period after "Stanford University" ("©  Stanford University. Stanford, California 94305." instead of "© Stanford University, Stanford, California 94305"). Is that right?

Here's a screenshot of that minor difference in the copyright string at the bottom.

![checking-that-i-understand-the-changes](https://user-images.githubusercontent.com/7118996/39334161-697c1ac4-4962-11e8-82f9-5e0e9d9c5575.png)

I don't know if these things matter to Rob or others, but for my own sake, was just curious what's changing. This all looks fine to me, so will leave it to the others to actually yay / nay these changes.

2018-04-26 22:14 UTC, caesar2164 commented
Thanks for the request for better info @mondiaz!

- There are header changes as well, but they are just in code. (Nothing changes visually)
- Correct, I show a whole bunch of screenshots, because part of the changes is better media query styling. (for phones, tablets, etc...)
- Correct, there are now more links, including the specifically requested `Privacy Policy`.
- Yep!

2018-04-26 22:25 UTC, mondiaz commented
@caesar2164 thanks! LGTM 👍

2018-04-27 19:35 UTC, stvstnfrd commented
@caesar2164 Can you link to where these styles came from?

2018-04-27 19:42 UTC, caesar2164 commented
Sure @stvstnfrd, I got them from here:
https://identity.stanford.edu/web-mobile.html

And specifically from this file:
https://www-media.stanford.edu/su-identity/css/su-identity.css

2018-04-27 22:25 UTC, stvstnfrd commented
@caesar2164 Can you add those links as comments somewhere relevant?

2018-04-27 22:26 UTC, stvstnfrd approved these changes
After you add comments linking to the documentation/references, +1

2018-04-27 22:26 UTC, stvstnfrd commented
and squash commits, presumably..

2018-04-27 22:38 UTC, merged