Move sidebar to top of course about in mobile
Stanford-Online/openedx-themes pull request #40
Opened 2018-07-06 19:51 UTC by caesar2164

2018-07-12 21:44 UTC, caesar2164 commented
Need to add window resize handler.

2018-07-12 21:46 UTC, stvstnfrd requested changes

2018-07-12 21:46 UTC, stvstnfrd commented on lagunita/lms/templates/courseware/course_about_js_extra.html
> +            courseDetails.css("margin-top", courseSidebarHeight);
Single quotes for non-interpolated strings.

2018-07-12 21:46 UTC, stvstnfrd commented on lagunita/lms/templates/courseware/course_about_js_extra.html
> +    var mobileWidth = 768;
Investigate options for sticking this in a variable. Ideally, the same variable will be used by the sass.

2018-07-12 21:59 UTC, stvstnfrd commented on lagunita/lms/templates/courseware/course_about_js_extra.html
> +            var courseSidebar = $('#content .course-sidebar');
Move this to the top of the function then bail if length != 1.

```js
var courseSidebar = $('#content .course-sidebar');
if (courseSidebar.length !== 1) {
    return;
}
// continue w/ resizing/etc...
```

2018-07-17 20:33 UTC, caesar2164 commented
this is getting pushed to after the Ginkgo merge

2018-07-17 20:33 UTC, closed without merging