Modify acoount activation email template
Stanford-Online/openedx-themes pull request #78
Opened 2019-04-05 21:42 UTC by tanyaxp

Modify account activation email text. This improves the user experience for auto
enrolled participants.

2019-04-05 21:43 UTC, tanyaxp commented
@stvstnfrd , @caesar2164 Could you please review this. Thanks!

2019-04-08 22:50 UTC, caesar2164 submitted a review, later dismissed

2019-04-09 18:32 UTC, stvstnfrd requested changes

2019-04-09 18:32 UTC, stvstnfrd commented on lagunita/lms/templates/emails/activation_email.txt
> +<%! from django.utils.translation import ugettext as _ %>
It's minor, but to keep these two files as in-sync as possible,
let's also include the mako comment;
it makes `diff`ing more in-line.

```
## mako
```

2019-04-09 18:33 UTC, stvstnfrd commented
@tanyaxp This branch also needs rebased now that the other PR merged to master.
Feel free to perform the rebase now (instead of waiting until "the end" of the PR).

2019-04-09 20:04 UTC, tanyaxp commented
@stvstnfrd Please take a look at this rebase. Thanks!

2019-04-09 20:29 UTC, stvstnfrd approved these changes

2019-04-09 20:34 UTC, merged