Track Google Analtyics tags used for registration
Stanford-Online/openedx-themes pull request #86
Opened 2019-08-02 21:21 UTC by stvstnfrd

Save the most recently-used Google Analtyics parameters and then save
them as a user attribute upon account registration.

Query String Parameters:
- utm_source
- utm_medium
- utm_campaign
- utm_term
- utm_content

This is cribbed from upstream [1].

- [1] https://github.com/edx/ecommerce-scripts/blob/master/gtm_scripts/utm_tracking/stage_utm_cookie.js

2019-08-02 21:27 UTC, stvstnfrd commented
![Screen Shot 2019-08-02 at 14 23 04](https://user-images.githubusercontent.com/7300975/62399571-1e6d1100-b531-11e9-84a9-5cf48aef2dea.png)


@jen-nifer This saves the most recent `utm` params into the `student_userattribute` table, with `name` values like:
- `registration_utm_source`
- `registration_utm_campaign`
- `registration_utm_medium`
- etc...

So now we know, at least for new account registration, where users came from :)

Note: the feature can be enabled/configured via Django Admin:
- `admin/student/registrationcookieconfiguration/add/`

2019-08-02 21:33 UTC, stvstnfrd commented
Sorry, just some more context...

All of the necessary python code already exists in platform (including the data/migration).
To take advantage of it, we just need to set the appropriate cookie in the prescribed format and if it's there, the backend/python code pulls it out and saves it to the DB automatically :)

2019-08-05 17:54 UTC, caesar2164 approved these changes
This seems good, and since upstream is using it, we know it works :)

2019-08-05 18:53 UTC, jen-nifer requested changes
Sounds good, but can we update PR references to "Analytics" for search results purposes?

2019-08-05 22:55 UTC, stvstnfrd commented
@jen-nifer Typo fixed in title and commit message.

2019-08-07 19:40 UTC, jen-nifer approved these changes

2019-08-07 22:08 UTC, merged